services:
  db:
    image: mysql:8.0.31
    container_name: db
    restart: always
    environment:
      MYSQL_PASSWORD: rootroot123!
      MYSQL_USER: newuser
      MYSQL_DATABASE: express
      MYSQL_ROOT_PASSWORD: rootroot123!
      MYSQL_PORT: 3306
    ports:
      - "3305:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 3

  client:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
